name: Swift CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.5'  # Specify the Swift version
    - name: Build and Run
      run: |
        swift build
        swift test
